version: "2"
services:
  adh:
    image: adguard/adguardhome
    volumes:
      - ./config:/opt/adguardhome/conf
      - ./data:/opt/adguardhome/work
      #- ../Certbot/ssl/archive/domain:/ssl
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 80:80/tcp
      - 443:443/tcp
      - 853:853/tcp
      - 3000:3000/tcp